package adhd

// Frame represents a cognitive vantage point for divergent analysis.
// Each frame re-poses the problem from a distinct expert perspective.
type Frame struct {
	ID            string   `json:"id"`
	Name          string   `json:"name"`
	Tags          []string `json:"tags"`
	VantagePrompt string   `json:"vantage_prompt"`
}

// Hypothesis is a candidate explanation generated by a single frame.
type Hypothesis struct {
	ID        string   `json:"id"`
	FrameID   string   `json:"frame_id"`
	Text      string   `json:"text"`
	Rationale string   `json:"rationale"`
	Evidence  []string `json:"evidence,omitempty"`
	Score     Score    `json:"score"`
	Depth     int      `json:"depth"`
	ParentID  string   `json:"parent_id,omitempty"`
}

// Score quantifies how promising a hypothesis is.
type Score struct {
	Likelihood float64 `json:"likelihood"`
	Impact     float64 `json:"impact"`
	Evidence   float64 `json:"evidence"`
	Total      float64 `json:"total"`
	Trap       string  `json:"trap,omitempty"`
}

// Branch groups the hypotheses produced by a single frame during diverge.
type Branch struct {
	FrameID    string       `json:"frame_id"`
	FrameName  string       `json:"frame_name"`
	Hypotheses []Hypothesis `json:"hypotheses"`
}

// Cluster groups hypotheses that share the same underlying failure mechanism.
type Cluster struct {
	Label         string   `json:"label"`
	Mechanism     string   `json:"mechanism"`
	HypothesisIDs []string `json:"hypothesis_ids"`
}

// DeepenedHypothesis extends a top hypothesis with investigation guidance.
type DeepenedHypothesis struct {
	HypothesisID    string       `json:"hypothesis_id"`
	Sketch          string       `json:"sketch"`
	LoadBearingRisk string       `json:"load_bearing_risk"`
	FirstStep       string       `json:"first_step"`
	ChildHypotheses []Hypothesis `json:"child_hypotheses,omitempty"`
}

// DiagnosisResult is the complete output of an ADHD diagnostic cycle.
type DiagnosisResult struct {
	Problem     string               `json:"problem"`
	Branches    []Branch             `json:"branches"`
	Clusters    []Cluster            `json:"clusters"`
	Shortlist   []Hypothesis         `json:"shortlist"`
	NonObvious  *Hypothesis          `json:"non_obvious,omitempty"`
	Traps       []Hypothesis         `json:"traps"`
	Deepened    []DeepenedHypothesis `json:"deepened"`
	Provocation string               `json:"provocation"`
}

// DiagnosisOptions controls the ADHD diagnostic cycle behavior.
type DiagnosisOptions struct {
	FrameCount  int    // Number of frames to use (default 5)
	TopK        int    // Number of top hypotheses to deepen (default 3)
	Depth       string // "quick", "standard", "deep"
	Concurrency int    // Max parallel frames (default 4)
}

// DefaultOptions returns sensible defaults for a diagnostic cycle.
func DefaultOptions() DiagnosisOptions {
	return DiagnosisOptions{
		FrameCount:  5,
		TopK:        3,
		Depth:       "standard",
		Concurrency: 4,
	}
}

// ClusterSnapshot is a serializable summary of cluster state used for prompt
// construction. It is built from a datasource.ClusterDataSource.
type ClusterSnapshot struct {
	ClusterVersion    string   `json:"cluster_version"`
	NodeCount         int      `json:"node_count"`
	NotReadyNodes     int      `json:"not_ready_nodes"`
	DegradedOperators []string `json:"degraded_operators"`
	FailedPods        []string `json:"failed_pods"`
	WarningEvents     []string `json:"warning_events"`
	MCPStatus         string   `json:"mcp_status"`
	NetworkType       string   `json:"network_type"`
	StorageIssues     []string `json:"storage_issues"`
}
